import { MigrationInterface, QueryRunner } from "typeorm";

export class NewsArticleEntity1772997192403 implements MigrationInterface {
    name = 'NewsArticleEntity1772997192403'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_a6c6e8b8e7c4c8d8b43b8bc5"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_a6c6e8b8e7c4c8d8b43b8bc8"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_a6c6e8b8e7c4c8d8b43b8bc9"`);
        await queryRunner.query(`ALTER TABLE "thread" DROP CONSTRAINT "FK_c69d28a5fa7dc4dd4dfb35b69b"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP CONSTRAINT "FK_f8c06b9b9b4f4c8d8b43b8bd4"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP CONSTRAINT "FK_f8c06b9b9b4f4c8d8b43b8bd5"`);
        await queryRunner.query(`ALTER TABLE "workers" DROP CONSTRAINT "FK_workers_task"`);
        await queryRunner.query(`ALTER TABLE "user_storage_location" DROP CONSTRAINT "FK_user_storage_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6c6e8b8e7c4c8d8b43b8bc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6c6e8b8e7c4c8d8b43b8bc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6c6e8b8e7c4c8d8b43b8bc9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69d28a5fa7dc4dd4dfb35b69b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8c06b9b9b4f4c8d8b43b8bd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8c06b9b9b4f4c8d8b43b8bd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tasks_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tasks_worker_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tasks_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_task_events_task_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workers_heartbeat"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workers_status"`);
        await queryRunner.query(`CREATE TYPE "public"."news_articles_newstype_enum" AS ENUM('article', 'video')`);
        await queryRunner.query(`CREATE TYPE "public"."news_articles_sourcetype_enum" AS ENUM('rss', 'youtube')`);
        await queryRunner.query(`CREATE TABLE "news_articles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(500) NOT NULL, "summary" text, "content" text, "url" character varying(1000) NOT NULL, "imageUrl" character varying(500), "newsType" "public"."news_articles_newstype_enum" NOT NULL DEFAULT 'article', "sourceName" character varying(100) NOT NULL, "sourceType" "public"."news_articles_sourcetype_enum" NOT NULL DEFAULT 'rss', "author" character varying(100), "publishedAt" TIMESTAMP NOT NULL, "aiSummary" text, "duration" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca1b67b1b6b2c382317bbd769dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ea0622735620e3b4c56e95a1a" ON "news_articles" ("newsType") `);
        await queryRunner.query(`CREATE INDEX "IDX_c10c8b4a207dd236ff84a2f2af" ON "news_articles" ("sourceName", "publishedAt") `);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "parentId"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "postType"`);
        await queryRunner.query(`ALTER TABLE "thread" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`CREATE TYPE "public"."post_type_enum" AS ENUM('TEXT', 'VIDEO', 'IMAGE')`);
        await queryRunner.query(`ALTER TABLE "post" ADD "type" "public"."post_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "thread" ADD "content" character varying`);
        await queryRunner.query(`ALTER TABLE "thread" ADD "isPinned" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "thread" ADD "authorId" uuid`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD "revokedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD "grantedById" uuid`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "maxConcurrentTasks" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('STANDARD', 'ADMIN', 'THREAD_ADMIN')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" TYPE "public"."user_role_enum" USING "role"::"text"::"public"."user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" SET DEFAULT 'STANDARD'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "content" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "authorId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "threadId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ALTER COLUMN "threadId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum" RENAME TO "task_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."tasks_status_enum" USING "status"::"text"::"public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."task_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."task_priority_enum" RENAME TO "task_priority_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('0', '1', '2', '3', '4')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" TYPE "public"."tasks_priority_enum" USING "priority"::"text"::"public"."tasks_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" SET DEFAULT '2'`);
        await queryRunner.query(`DROP TYPE "public"."task_priority_enum_old"`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."workers_status_enum" AS ENUM('IDLE', 'BUSY', 'OFFLINE')`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "status" "public"."workers_status_enum" NOT NULL DEFAULT 'IDLE'`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "lastHeartbeatAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "startedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "migration_state" ALTER COLUMN "shardCount" SET DEFAULT '8'`);
        await queryRunner.query(`ALTER TABLE "user_storage_location" ALTER COLUMN "verificationStatus" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_10f8a3df60c9e7771cefba6c35" ON "tasks" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4499277a718943137c34faa91c" ON "tasks" ("workerId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_834b57735f213c3c2d642baf98" ON "tasks" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac3e575c5fed4c0127da3b32bd" ON "task_events" ("taskId", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_948cf309979be7fcda1079b708" ON "workers" ("lastHeartbeatAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2aa2021ace8583f566edbbe18d" ON "workers" ("status") `);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD CONSTRAINT "UQ_a49e20ca79770a511ad07d54d78" UNIQUE ("userId", "threadId")`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_b148d2f5a22e7904160c69b09f8" FOREIGN KEY ("threadId") REFERENCES "thread"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread" ADD CONSTRAINT "FK_7060c5e0b10f141ce2ca501bc13" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD CONSTRAINT "FK_2a4a73236838170a76f448213f6" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD CONSTRAINT "FK_81925e4d79dfbfc194097cebf7e" FOREIGN KEY ("threadId") REFERENCES "thread"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD CONSTRAINT "FK_98cdabdf0599df92c9729e1a039" FOREIGN KEY ("grantedById") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP CONSTRAINT "FK_98cdabdf0599df92c9729e1a039"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP CONSTRAINT "FK_81925e4d79dfbfc194097cebf7e"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP CONSTRAINT "FK_2a4a73236838170a76f448213f6"`);
        await queryRunner.query(`ALTER TABLE "thread" DROP CONSTRAINT "FK_7060c5e0b10f141ce2ca501bc13"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_b148d2f5a22e7904160c69b09f8"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP CONSTRAINT "UQ_a49e20ca79770a511ad07d54d78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2aa2021ace8583f566edbbe18d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_948cf309979be7fcda1079b708"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac3e575c5fed4c0127da3b32bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_834b57735f213c3c2d642baf98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4499277a718943137c34faa91c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10f8a3df60c9e7771cefba6c35"`);
        await queryRunner.query(`ALTER TABLE "user_storage_location" ALTER COLUMN "verificationStatus" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "migration_state" ALTER COLUMN "shardCount" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "startedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workers" ALTER COLUMN "lastHeartbeatAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."workers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "workers" ADD "status" character varying(20) NOT NULL DEFAULT 'IDLE'`);
        await queryRunner.query(`CREATE TYPE "public"."task_priority_enum_old" AS ENUM('CRITICAL', 'HIGH', 'NORMAL', 'LOW', 'IDLE')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" TYPE "public"."task_priority_enum_old" USING "priority"::"text"::"public"."task_priority_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "priority" SET DEFAULT 'NORMAL'`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_priority_enum_old" RENAME TO "task_priority_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."task_status_enum_old" AS ENUM('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."task_status_enum_old" USING "status"::"text"::"public"."task_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum_old" RENAME TO "task_status_enum"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ALTER COLUMN "threadId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "threadId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "authorId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "content" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('STANDARD', 'ADMIN', 'MODERATOR')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "role" SET DEFAULT 'STANDARD'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "workers" DROP COLUMN "maxConcurrentTasks"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP COLUMN "grantedById"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" DROP COLUMN "revokedAt"`);
        await queryRunner.query(`ALTER TABLE "thread" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "thread" DROP COLUMN "isPinned"`);
        await queryRunner.query(`ALTER TABLE "thread" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."post_type_enum"`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "thread" ADD "createdById" uuid`);
        await queryRunner.query(`ALTER TABLE "post" ADD "postType" character varying NOT NULL DEFAULT 'comment'`);
        await queryRunner.query(`ALTER TABLE "post" ADD "parentId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c10c8b4a207dd236ff84a2f2af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ea0622735620e3b4c56e95a1a"`);
        await queryRunner.query(`DROP TABLE "news_articles"`);
        await queryRunner.query(`DROP TYPE "public"."news_articles_sourcetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."news_articles_newstype_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_workers_status" ON "workers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_workers_heartbeat" ON "workers" ("lastHeartbeatAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_task_events_task_timestamp" ON "task_events" ("taskId", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_tasks_created" ON "tasks" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_tasks_worker_status" ON "tasks" ("status", "workerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_tasks_user_status" ON "tasks" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8c06b9b9b4f4c8d8b43b8bd5" ON "thread_admin" ("threadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8c06b9b9b4f4c8d8b43b8bd4" ON "thread_admin" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69d28a5fa7dc4dd4dfb35b69b" ON "thread" ("createdById") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6c6e8b8e7c4c8d8b43b8bc9" ON "post" ("parentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6c6e8b8e7c4c8d8b43b8bc8" ON "post" ("threadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6c6e8b8e7c4c8d8b43b8bc5" ON "post" ("authorId") `);
        await queryRunner.query(`ALTER TABLE "user_storage_location" ADD CONSTRAINT "FK_user_storage_user" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workers" ADD CONSTRAINT "FK_workers_task" FOREIGN KEY ("currentTaskId") REFERENCES "tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD CONSTRAINT "FK_f8c06b9b9b4f4c8d8b43b8bd5" FOREIGN KEY ("threadId") REFERENCES "thread"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread_admin" ADD CONSTRAINT "FK_f8c06b9b9b4f4c8d8b43b8bd4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "thread" ADD CONSTRAINT "FK_c69d28a5fa7dc4dd4dfb35b69b" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_a6c6e8b8e7c4c8d8b43b8bc9" FOREIGN KEY ("parentId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_a6c6e8b8e7c4c8d8b43b8bc8" FOREIGN KEY ("threadId") REFERENCES "thread"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_a6c6e8b8e7c4c8d8b43b8bc5" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
